language: java
jdk:
  - openjdk8
branches:
  only:
    - main
before_install:
  - chmod +x gradlew
# Travis CI sever home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
before_deploy:
  - zip -r springboot_web_prj *
  - mkdir -p deploy
  - mv springboot_web_prj.zip deploy/springboot_web_prj.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yangbum-springbootweb-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main


#CI
notifications:
  email:
    recipients:
      - very3sky@gmail.com