language: java
jdk:
  - openjdk8
branches:
  only:
    - main
before_install:
  - chmod +x gradlew
# Travis CI sever home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI
notifications:
  email:
    recipients:
      - very3sky@gmail.com