language: java
jdk:
  - openjdk8
branches:
  only:
    - main
before_install:
  - chmod +x gradlew
# Travis CI sever home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip



  # - zip -r springboot_web_prj *
  # - mkdir -p deploy
  # - mv springboot_web_prj.zip deploy/springboot_web_prj.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yangbum-springbootweb-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yangbum-springbootweb-build
    key: springboot_web_prj.zip #키가 그룹안에 키 인가 그냥 그거 키인가

    bundle_type: zip
    application: springbootcodedeploy

    deployment_group: springboot-us-east
    region: us-east-1
    wait-util-deployed: true
    on:
      branch: main



#CI
notifications:
  email:
    recipients:
      - very3sky@gmail.com