language: java
jdk:
  - openjdk8
branches:
  only:
    - master
# Travis CI sever home
cache: :
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "/.gradlew clean build"

#CI complete to alram email
notifications:
  email:
    recipients:
      - very2sky@naver.com